# Generated by Django 3.2.4 on 2021-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productocelular',
            fields=[
                ('idProductocelular', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcioncelular', models.CharField(max_length=100, verbose_name='Descripción')),
                ('preciocelular', models.IntegerField(verbose_name='Precio Unitario')),
                ('stockcelular', models.IntegerField(verbose_name='Stock')),
                ('imagencelular', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'productocelular',
                'verbose_name_plural': 'productoscelular',
                'ordering': ['descripcioncelular'],
            },
        ),
        migrations.CreateModel(
            name='roductoRi',
            fields=[
                ('idProductoRi', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionRi', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precioRi', models.IntegerField(verbose_name='Precio Unitario')),
                ('stockRi', models.IntegerField(verbose_name='Stock')),
                ('imagenRi', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'productoRi',
                'verbose_name_plural': 'productosRi',
                'ordering': ['descripcionRi'],
            },
        ),
    ]
